version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-rest-slimphp
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - mysql
    environment:
      DB_HOSTNAME: mysql
      DB_DATABASE: api_rest_slimphp
      DB_USERNAME: app
      DB_PASSWORD: password
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: api_rest_slimphp
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
